services:
  latex:
    build: .
    volumes:
      - ./src:/src
      - ./output:/output
    command:
      - "pdflatex"
      - "-output-directory=/output"
      - "-output-format=pdf"
      - "/src/curriculum.tex"
